apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
    selector:
        app: voms-elasticsearch
    ports:      
      - name: port9200
        port: 9200
      - name: port9300
        port: 9300              
