kind: Service
apiVersion: v1
metadata:
  name: file-server
spec:
  selector:
    app: voms-file-server
  ports:
    - name: port2049
      port: 2049
    - name: port20048
      port: 20048
    - name: port111
      port: 111      
  clusterIP: 10.110.111.197

