apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
    selector:
      app: voms-mailhog
    ports:      
      - name: port1025
        port: 1025
      - name: port8025
        port: 8025   
