apiVersion: apps/v1
kind: Deployment
metadata:
  name: voms-batch-deployment
  labels:
    app: voms-batch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voms-batch
  template:
    metadata:
      name: voms-batch
      labels:
          app: voms-batch
    spec:
      volumes:
        - name: voms-apps-data
          nfs:
            path: /
            server: 10.110.111.197
      containers:
      - name: voms-batch
        image: 127.0.0.1:6000/voms-batch:edge
        volumeMounts:
            - mountPath: /voms/data
              name: voms-apps-data

