apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: voms-logstash-statefulset
  labels:
    app: voms-logstash-statefulset
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd          
spec:
  serviceName: "voms-logstash"
  podManagementPolicy: "Parallel"
  replicas: 3
  selector:
    matchLabels:
      app: voms-logstash
  volumeClaimTemplates:
    - metadata:
        name: voms-logstash-data
        labels:
          customer: kubernetes_topup
          product: topup
          owner: mohamed_elbahrawy
          purpose: rnd              
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi                      
  template:    
    metadata:
      name: voms-logstash
      labels:
        app: voms-logstash
        customer: kubernetes_topup
        product: topup
        owner: mohamed_elbahrawy
        purpose: rnd              
    spec:  
      initContainers:      
         - name: fix-the-volume-permission
           image: busybox
           command:
           - sh
           - -c
           - chown -R 1000:1000 /usr/share/logstash/data
           securityContext:
             privileged: true
           volumeMounts:
           - name: voms-logstash-data
             mountPath: /usr/share/logstash/data    
      containers:
        - image: docker.elastic.co/logstash/logstash-oss:6.6.0
          name: voms-logstash
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/config/pipelines.yml
              subPath: pipelines.yml
            - name: logstash-pipelines
              mountPath: /voms/pipelines
            - name: voms-logstash-data
              mountPath: /usr/share/logstash/data                
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: logstash-pipelines
          configMap:
            name: logstash-pipelines

