apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: voms-mailhog-statefulset
  labels:
    app: voms-mailhog-statefulset
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd          
spec:
  serviceName: "voms-mailhog"
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      app: voms-mailhog
  template:    
    metadata:
      name: voms-mailhog
      labels:
        app: voms-mailhog
        customer: kubernetes_topup
        product: topup
        owner: mohamed_elbahrawy
        purpose: rnd              
    spec:
      containers:
      - name: voms-mailhog
        image: mailhog/mailhog

