package com.optiva.topup.voms.common.types;

public enum BatchOrderType {

  VOUCHER_CREATION_BATCH_ORDER,

  PRODUCTION_FILE_CREATION_BULK_ORDER,
  PRODUCTION_FILE_CREATION_LIST_ORDER,

  CREATE_VOUCHER_DESTROY_BULK_ORDER,
  CREATED_VOUCHER_ACTIVATION_BULK_ORDER,
  ACTIVE_VOUCHER_BLOCKING_BULK_ORDER,
  BLOCKED_VOUCHER_ACTIVATION_BULK_ORDER,
  PENDING_USAGE_VOUCHER_ACTIVATION_BULK_ORDER,
  PENDING_USAGE_VOUCHER_BLOCKING_BULK_ORDER,
  PENDING_USAGE_VOUCHER_USING_BULK_ORDER,

  ACTIVE_VOUCHER_BLOCKING_LIST_ORDER,
  BLOCKED_VOUCHER_ACTIVATION_LIST_ORDER,
  CREATED_VOUCHER_ACTIVATION_LIST_ORDER,
  CREATED_VOUCHER_DESTROY_LIST_ORDER,
  PENDING_USAGE_VOUCHER_ACTIVATION_LIST_ORDER,
  PENDING_USAGE_VOUCHER_BLOCKING_LIST_ORDER,
  PENDING_USAGE_VOUCHER_USING_LIST_ORDER,

  CREATED_VOUCHER_MODIFICATION_BULK_ORDER,
  BLOCKED_VOUCHER_MODIFICATION_BULK_ORDER,

  CREATED_VOUCHER_MODIFICATION_LIST_ORDER,
  BLOCKED_VOUCHER_MODIFICATION_LIST_ORDER,

}
