package com.optiva.topup.voms.common.types;

public enum VoucherPolicyType {
  ACTIVE_VOUCHER_BLOCKING_POLICY,
  BLOCKED_VOUCHER_DELETION_POLICY,
  CREATED_VOUCHER_DESTROYING_POLICY,
  DELETED_VOUCHER_DESTROYING_POLICY,
  DESTROYED_VOUCHER_POLICY,
  PENDING_USAGE_VOUCHER_BLOCKING_POLICY,
  PRODUCTION_VOUCHER_DESTROYING_POLICY,
  USED_VOUCHER_DELETION_POLICY
}
