apiVersion: v1
kind: Service
metadata:
  name: db-management
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_bahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-db-management
    ports:
      - name: port3306
        port: 3306
      - name: port1186
        port: 1186
