apiVersion: v1
kind: Service
metadata:
  name: db-ndb1
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-db-ndb1
    ports:
      - name: port3306
        port: 3306
      - name: port1186
        port: 1186
    clusterIP: None

