apiVersion: v1
kind: Service
metadata:
  name: db-server
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
        client: db-server
    ports:
      - name: port3306
        port: 3306
      - name: port1186
        port: 1186
