apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-elasticsearch-data
    ports:      
      - name: port9200
        port: 9200
      - name: port9300
        port: 9300      
    clusterIP: None

