apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
        app: voms-elasticsearch 
    ports:      
      - name: elasticsearch-port9200
        port: 9200
      - name: elasticsearch-port9300
        port: 9300
        
