apiVersion: v1
kind: Service
metadata:
  name: kafka2
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-kafka2
    ports:      
      - name: port9092
        port: 9092
    clusterIP: None
