apiVersion: v1
kind: Service
metadata:
  name: kafka3
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-kafka3
    ports:      
      - name: port9093
        port: 9093
    clusterIP: None
