apiVersion: v1
kind: Service
metadata:
  name: kafka1
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-kafka1
    ports:      
      - name: port9091
        port: 9091      
    clusterIP: None
