apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-kibana
    ports:      
      - name: port5601
        port: 5601
        
