apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-mailhog
    ports:      
      - name: port1025
        port: 1025
      - name: port8025
        port: 8025        
        
