apiVersion: v1
kind: Service
metadata:
  name: voms-security
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
        app: voms-security
    ports:      
      - name: port8080
        port: 8080    
