apiVersion: v1
kind: Service
metadata:
  name: voms-soap
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_bahrawy
    purpose: rnd        
spec:
    selector:
        app: voms-soap
    ports:      
      - name: port8080
        port: 8080              
