apiVersion: v1
kind: Service
metadata:
  name: voms-web
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd      
spec:
    selector:
      app: voms-web
    ports:      
      - name: port80
        port: 80
