apiVersion: v1
kind: Service
metadata:
  name: zookeeper2
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-zookeeper2
    ports:      
      - name: port2182
        port: 2182      
      - name: port22888
        port: 22888
      - name: port23888
        port: 23888
    clusterIP: None
