apiVersion: v1
kind: Service
metadata:
  name: zookeeper3
  labels:
    customer: kubernetes_topup
    product: topup
    owner: mohamed_elbahrawy
    purpose: rnd        
spec:
    selector:
      app: voms-zookeeper3
    ports:      
      - name: port2183
        port: 2183      
      - name: port32888
        port: 32888
      - name: port33888
        port: 33888
    clusterIP: None
