apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: voms-elasticsearch-statefulset
  labels:
    app: voms-elasticsearch-statefulset
spec:
  serviceName: "voms-elasticsearch"
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      app: voms-elasticsearch
  volumeClaimTemplates:
    - metadata:
        name: voms-elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi          
  template:    
    metadata:
      name: voms-elasticsearch
      labels:
        app: voms-elasticsearch
    spec:
      initContainers:      
         - name: fix-the-volume-permission
           image: busybox
           command:
           - sh
           - -c
           - chown -R 1000:1000 /usr/share/elasticsearch/data
           securityContext:
             privileged: true
           volumeMounts:
           - name: voms-elasticsearch-data
             mountPath: /usr/share/elasticsearch/data      
         - name: increase-the-vm-max-map-count
           image: busybox
           command:
           - sysctl
           - -w
           - vm.max_map_count=262144
           securityContext:
             privileged: true      
         - name: increase-the-ulimit
           image: busybox
           command:
           - sh
           - -c
           - ulimit -n 65536
           securityContext:
             privileged: true
      containers:
        - name: voms-elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0      
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: voms-elasticsearch-data
          env:      
            - name: "cluster.name"
              value: "voms"
