apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: voms-kafka-statefulset
  labels:
    app: voms-kafka-statefulset
spec:
  serviceName: "voms-kafka"
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      app: voms-kafka
  volumeClaimTemplates:
    - metadata:
        name: voms-kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi                
  template:    
    metadata:
      name: voms-kafka
      labels:
        app: voms-kafka
    spec:
      containers:
        - image: confluentinc/cp-kafka
          name: voms-kafka
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: voms-kafka-data
          env:
            - name: "KAFKA_ZOOKEEPER_CONNECT"
              value: "zookeeper:2181"
            - name: "KAFKA_ADVERTISED_LISTENERS"
              value: "INNER://kafka:29092,OUTER://localhost:9092"
            - name: "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP"
              value: "INNER:PLAINTEXT,OUTER:PLAINTEXT"
            - name: "KAFKA_INTER_BROKER_LISTENER_NAME"
              value: "INNER"
            - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
              value: "1"

